//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorTutorial.Components.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorTutorial.Components.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Menu .
        /// </summary>
        public static string i18n_Actual_Menu {
            get {
                return ResourceManager.GetString("i18n_Actual_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On start up the last active page will be loaded always.
        /// </summary>
        public static string i18n_Always_Last_Active_Site {
            get {
                return ResourceManager.GetString("i18n_Always_Last_Active_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string i18n_Button_Load {
            get {
                return ResourceManager.GetString("i18n_Button_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose menu items to delete.
        /// </summary>
        public static string i18n_Choose_Items_To_Delete {
            get {
                return ResourceManager.GetString("i18n_Choose_Items_To_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose site to edit.
        /// </summary>
        public static string i18n_Choose_Markdown_To_Edit {
            get {
                return ResourceManager.GetString("i18n_Choose_Markdown_To_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last page visited is opened when the page is called up again.&lt;br /&gt;To do this, the site&apos;s cookies are processed using a&lt;a class=&quot;link&quot; href=&quot;https://blazor-university.com/javascript-interop/&quot;&gt;Blazor Interop &lt;/a&gt; Call.&lt;br /&gt;To test, simply delete the site&apos;s cookies, close the browser and land on the home page.&lt;br /&gt;Now if you navigate to another site, close the browser&lt;br /&gt;and if you open it again, you will be redirected to the last page you visited..
        /// </summary>
        public static string i18n_cookie_handling {
            get {
                return ResourceManager.GetString("i18n_cookie_handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string i18n_Delete {
            get {
                return ResourceManager.GetString("i18n_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully, page will be reloaded.
        /// </summary>
        public static string i18n_Deleted_Successfully {
            get {
                return ResourceManager.GetString("i18n_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for menu path please use the &quot;Link&quot;entries).
        /// </summary>
        public static string i18n_For_Menu_Path {
            get {
                return ResourceManager.GetString("i18n_For_Menu_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details.
        /// </summary>
        public static string i18n_Get_Details {
            get {
                return ResourceManager.GetString("i18n_Get_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string i18n_Greeting {
            get {
                return ResourceManager.GetString("i18n_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide loading animation.
        /// </summary>
        public static string i18n_Hide_Loading_Animation {
            get {
                return ResourceManager.GetString("i18n_Hide_Loading_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The loading animation is created as an overlay with a standard animation in the menu&lt;br /&gt;and can thus be used from any page without having to re-integrate the animation each time..
        /// </summary>
        public static string i18n_loading_animation {
            get {
                return ResourceManager.GetString("i18n_loading_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter markdown text here.
        /// </summary>
        public static string i18n_Mark_Down_Editor_Input {
            get {
                return ResourceManager.GetString("i18n_Mark_Down_Editor_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown filename (without extension) - Has to be unique because it will be overridden otherwise.
        /// </summary>
        public static string i18n_Mark_Down_Name {
            get {
                return ResourceManager.GetString("i18n_Mark_Down_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name menu.
        /// </summary>
        public static string i18n_Mark_Down_Text {
            get {
                return ResourceManager.GetString("i18n_Mark_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can delete menu entries.
        /// </summary>
        public static string i18n_Menu_Editor_Description {
            get {
                return ResourceManager.GetString("i18n_Menu_Editor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menupath (Devided by Slash, max. 2 layers, , f.e. &quot;components/test&quot;).
        /// </summary>
        public static string i18n_Menu_Path {
            get {
                return ResourceManager.GetString("i18n_Menu_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molar mass.
        /// </summary>
        public static string i18n_MudBlazor_Table_Header_MolarMass {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Header_MolarMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string i18n_MudBlazor_Table_Header_Name {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string i18n_MudBlazor_Table_Header_Number {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Header_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string i18n_MudBlazor_Table_Header_Position {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Header_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string i18n_MudBlazor_Table_Header_Sign {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Header_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item per page.
        /// </summary>
        public static string i18n_MudBlazor_Table_RowsPerPage {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string i18n_MudBlazor_Table_Title {
            get {
                return ResourceManager.GetString("i18n_MudBlazor_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string i18n_NavMenu_MarkDown_Components {
            get {
                return ResourceManager.GetString("i18n_NavMenu_MarkDown_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Down Editor.
        /// </summary>
        public static string i18n_NavMenu_MarkDown_MarkDownEditor {
            get {
                return ResourceManager.GetString("i18n_NavMenu_MarkDown_MarkDownEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Down Viewer.
        /// </summary>
        public static string i18n_NavMenu_MarkDown_MarkDownViewer {
            get {
                return ResourceManager.GetString("i18n_NavMenu_MarkDown_MarkDownViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MudBlazor.
        /// </summary>
        public static string i18n_NavMenu_MarkDown_MudBlazor {
            get {
                return ResourceManager.GetString("i18n_NavMenu_MarkDown_MudBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string i18n_NavMenu_MarkDown_MudBlazorTable {
            get {
                return ResourceManager.GetString("i18n_NavMenu_MarkDown_MudBlazorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification is implemented via an application state.&lt;br /&gt;Here, a class is integrated centrally via dependency injection&lt;br /&gt;and then used as a central point of contact from several components.&lt;br /&gt;The concept is very similar to that of &lt;a class =&quot;link&quot; href=&quot;https://redux.js.org/&quot;&gt;Redux&lt;/a&gt;..
        /// </summary>
        public static string i18n_notification {
            get {
                return ResourceManager.GetString("i18n_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification example via centralized state.
        /// </summary>
        public static string i18n_Notification_Example {
            get {
                return ResourceManager.GetString("i18n_Notification_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press button to load.
        /// </summary>
        public static string i18n_Press_Button_Load {
            get {
                return ResourceManager.GetString("i18n_Press_Button_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string i18n_Save {
            get {
                return ResourceManager.GetString("i18n_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved, page will be reloaded.
        /// </summary>
        public static string i18n_Saved_Successfully {
            get {
                return ResourceManager.GetString("i18n_Saved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page can only be accessed after authorization from the bridging IT tenant, as it has been provided with your authorize attribute..
        /// </summary>
        public static string i18n_Secured_Page {
            get {
                return ResourceManager.GetString("i18n_Secured_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a value from the settings.
        /// </summary>
        public static string i18n_Setting {
            get {
                return ResourceManager.GetString("i18n_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application settings are read via a service directly from the IConfiguration provided via the dependency injection and output in typed form..
        /// </summary>
        public static string i18n_settings {
            get {
                return ResourceManager.GetString("i18n_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show loading animation.
        /// </summary>
        public static string i18n_Show_Loading_Animation {
            get {
                return ResourceManager.GetString("i18n_Show_Loading_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        public static string i18n_Show_Notification {
            get {
                return ResourceManager.GetString("i18n_Show_Notification", resourceCulture);
            }
        }
    }
}
